### ISSUE TITLE
Prettier Printing

### ISSUE THREAD

**Issue by fowles** [mtshiba/ruast#1]
When generating code, I often see extra parens and missing indenting.  For example:

```rust
fn square(num: i32) -> i32 {
((num * num) + num)
}
```

I plan on making heavy use of ruast and would like to fix these things, but the project has been idle for some time.  So I have several related questions:

- Would PRs to improve this be accepted?
- Assuming that I build a track record of good changes, would you be open to joint maintenance of the project? (I am mildly concerned about timezone lag for features and crate releases)

**Comment by mtshiba** [comment]
Hi, thank you for considering contributing to this project! Contributions are always welcome.
This crate was originally created as a sub-crate of my personal project, but that project is currently suspended, so development of this crate has also stalled temporarily. However, I have not abandoned the development of either crate.

I had also hoped that AST formatting could be implemented, but it is a bit cumbersome, so I have been pending (because it is sufficient for my purpose to dump and then format using rustfmt). I'd be very grateful if you implement this, and I would be willing to grant you the right to co-manage the repository and crate if you'd like me to merge PRs and make releases reflecting your contributions quickly.

If you have any questions, feel free to ask in the discussions.

**Comment by fowles** [comment]
That is great to hear!  I will start sending you PRs and when you are satisfied with the quality level of them we can expand to comaintenance. :)

**Comment by fowles** [comment]
While exploring this problem space a bit more, I discovered https://github.com/dtolnay/syn, https://github.com/dtolnay/quote, and https://github.com/dtolnay/prettyplease.

These together fit my problem really well, so I am shifting over to that.  I really appreciate your willingness to be share the repo, but I don't think I will follow up on that.  The PRs that I have already sent out to you are a nice improvement if you want them though!
